### ISSUE TITLE
Error while compiling

### ISSUE THREAD

**Issue by jerryzj** [OpenChannelSSD/pblk-tools#1]
Hello,

When I try "make", there is an error shows that it can't find " -ludev " in folder " /usr/bin/ld ".
Could you please help me? I can't find anything about -ludev on google.

Error screenshot: http://imgur.com/a/XOhgk

Thanks,
Jerry

**Comment by MatiasBjorling** [comment]
Hi,

You are missing libudev. If you're using Ubuntu, install with apt-get
install libudev-dev.

-Matias

**Comment by jerryzj** [comment]
@MatiasBjorling Thanks for your help, it works now :)

Jerry
